os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - os: windows

dist: xenial
language: c

addons:
  apt:
    packages:
      - rpm
      - wine
      - fakeroot

script:
  - echo $JAVA_HOME
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run -a ./gradlew test all; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./gradlew current; fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install jdk8
      JAVA_HOME=c:/Program\ Files/Java/jdk1.8.0_* ./gradlew --info test win-installer
    fi
